dist: trusty
language: php

php:
    - 7.2

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --dev --prefer-dist --no-suggest

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml
