dist: trusty
language: php

matrix:
  include:
    - php: 7.1
      env: LARAVEL_VERSION=5.7.*
    - php: 7.2
      env: LARAVEL_VERSION=5.7.*

before_install:
  - composer require "laravel/framework:${LARAVEL_VERSION}" --no-update

install:
  - composer update --prefer-source --no-interaction

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml