name: Run tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    name: Test-PHP${{matrix.php}}-L${{matrix.laravel}}

    strategy:
     matrix:
        php: [8.0, 8.1, 8.2]
        laravel: [10.*, 9.*]
        include:
          - laravel: 10.*
            testbench: ^8.0
          - laravel: 9.*
            testbench: ^7.0
        exclude:
          - laravel: 10.*
            php: 8.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php}}

      - name: Install deps
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --no-interaction

      - name: Run tests
        run: vendor/bin/phpunit --testdox --coverage-text
